### ISSUE TITLE
Items/mobs thrown into portal appear at the location of standard 1:8 scale

### ISSUE THREAD

**Issue by FlandreS** [OLEGSHA/CustomNetherScale#2] opened 2022-01-02 08:33 UTC
Hiyo! As the title mentions, entities other than the player still arrive at the 'original'/vanilla location.

An example: A portal at x:128 y:64 z:128 - throwing items into it, they arrive at x:16 y:64 z:16 even if the scale is set lower or higher in the config. Due to vanilla portal-sync mechanics this might not happen over short distances but across anything larger than a couple hundred blocks it can start to effectively 'void' items/mobs.

This works backwards too, pushing mobs through a portal inside the nether at x:1000 y:64 z:1000 will create a new overworld portal at x:8000 y:64 z:8000 and deposit them there.

**Comment by OLEGSHA** [comment] 2022-01-02 11:08
Huh, that's weird. I'll see what can be done about it in the next couple days. I suppose this is reproducible without any other mods on pure Forge, right?

**Comment by FlandreS** [comment] 2022-01-02 13:32
Hmm, it actually works just fine in a pure Forge install. My bad. This must be another Cauldron/Thermos issue. I've got very little experience with code but giving it confused look-over, it looks like teleporting entities is getting handled by bukkit and that's the problem I was experiencing.

Something in here, perhaps - https://github.com/CyberdyneCC/Thermos/blob/master/patches/net/minecraft/entity/Entity.java.patch

**Comment by OLEGSHA** [comment] 2022-01-02 20:13
I'm using Thermos myself, and we haven't noticed this issue yet - either because we don't have it, or because nobody ever paid attention to that. I'll test entity teleports on our server, and if the issue is with Thermos or any of its ascendants, I'll try to resolve the issue

**Comment by OLEGSHA** [comment] 2022-11-11 11:50
I'm closing this for now under "can't reproduce". If anyone still experiences this issue, feel free to reopen it.

**Closed as not planned by OLEGSHA** 2022-11-11 11:50 UTC
